language: python
python:
  - "2.7"
  - "3.7"
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - parts/node
    - $HOME/buildout-cache
addons:
  firefox: 45.8.0esr
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
  exclude:
    - python: "2.7"
    - python: "3.7"
  allow_failures:
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install cookiecutter
  - export DISPLAY=:99.0
  - pip install -r requirements.txt
  # FIXME: I have no idea how and why six==1.11.0 is being installed
  - pip uninstall -y six
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -t 10 -c travis.cfg
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - make code-analysis
  - make test
